name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

permissions: {}

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checkout additional repo
        uses: actions/checkout@v6
        with:
          repository: frasermolyneux/.github-copilot
          ref: refs/tags/v0.1.0
          path: .github-copilot

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
            dotnet-version: |
              9.0.x
              10.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: Build MCP server
        working-directory: .github-copilot/mcp-server
        run: npm ci && npm run build
